In [4]:
import numpy as np
import matplotlib.pyplot as plt

In [5]:
X = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
              [1, 1, 2, 5, 3, 0, 5, 10, 1, 2],
              [500, 700, 750, 600, 1450, 800, 1500, 2000, 450, 1000],
              [1, 1, 2, 1, 2,  1, 3, 3, 1, 2]], dtype = np.float64)
y = np.array([0, 0, 1, 0, 1, 0, 1, 0, 1, 1], dtype = np.float64)

In [6]:
def calc_std_feat(x):
    res = (x - x.mean()) / x.std()
    return res

In [7]:
X_st = X.copy()
X_st[2, :] = calc_std_feat(X[2, :])

In [8]:
def calc_logloss(y, y_pred):
    err = - np.mean(y * np.log(np.where(y_pred==0.0, np.ones(len(y_pred)), y_pred)) + (1.0 - y) * np.log(1.0 - np.where(y_pred==1.0, np.zeros(len(y_pred)), y_pred)))
    err = np.sum(err)
    return err

In [9]:
def sigmoid(z):
    res = 1 / (1 + np.exp(-z))
    return res

In [10]:
z = np.linspace(-10, 10, 101)

In [11]:
def eval_model(X, y, iterations, alpha=1e-4):
    np.random.seed(42)
    W = np.random.randn(X.shape[0])
    n = X.shape[1]
    for i in range(1, iterations+1):
        z = np.dot(W, X)
        y_pred = sigmoid(z)
        err = calc_logloss(y, y_pred)
        W -= alpha * (1/n * np.dot((y_pred - y), X.T))
        if i % (iterations / 10) == 0:
            print(i, W, err)
    return W

In [12]:
W = eval_model(X_st, y, iterations=5000, alpha=1e-4)

500 [ 0.47822106 -0.20918419  0.64605995  1.49531432] 1.0559639161585663
1000 [ 0.46074241 -0.27647603  0.64395686  1.46891696] 0.945214871179169
1500 [ 0.44435675 -0.33951515  0.64152026  1.44406912] 0.8478360281905125
2000 [ 0.42913461 -0.39751872  0.63899625  1.42106251] 0.7651177745022372
2500 [ 0.41513888 -0.44956784  0.63671032  1.40023024] 0.6981293270105478
3000 [ 0.40240136 -0.49488241  0.63498247  1.38184975] 0.6468813805442176
3500 [ 0.39088925 -0.53321212  0.63401986  1.36601535] 0.6097021563515638
4000 [ 0.38049869 -0.56497213  0.63387116  1.35259671] 0.5836774145473647
4500 [ 0.37108342 -0.59102182  0.63446603  1.3413119 ] 0.5657147376221167
5000 [ 0.36249064 -0.61234585  0.63568321  1.33183158] 0.5532737788236778


## Д/з

1*. Измените функцию calc_logloss так, чтобы нули по возможности не попадали в np.log.

In [13]:
def calc_logloss(y, y_pred):
    err = - np.mean(y * np.log(np.where(y_pred==0.0, np.ones(len(y_pred)), y_pred)) + (1.0 - y) * np.log(1.0 - np.where(y_pred==1.0, np.zeros(len(y_pred)), y_pred)))
    err = np.sum(err)
    return err

2. Подберите аргументы функции eval_model для логистической регрессии таким образом, чтобы log loss был минимальным.

In [14]:
W = eval_model(X_st, y, iterations=1000, alpha=2000)

100 [-6357.77170631 -2101.44828591   213.69195045  8269.67245078] 5.440557802491661
200 [-10957.79690882  -1501.47348841  -2230.10185238  11069.64724828] 34.70601776610128
300 [-11796.37643273  -1701.47348841  -2608.01432146  10831.06772436] 3.511047008747956e-12
400 [-11796.37643344  -1701.47348841  -2608.01432121  10831.06772365] 3.511047008747956e-12
500 [-11796.37643414  -1701.47348841  -2608.01432096  10831.06772295] 3.511047008747956e-12
600 [-11796.37643484  -1701.47348841  -2608.0143207   10831.06772225] 3.511035906517709e-12
700 [-11796.37643554  -1701.47348841  -2608.01432045  10831.06772155] 3.511035906517709e-12
800 [-11796.37643625  -1701.47348841  -2608.0143202   10831.06772085] 3.511024804287463e-12
900 [-11796.37643695  -1701.47348841  -2608.01431994  10831.06772014] 3.511024804287463e-12
1000 [-11796.37643765  -1701.47348841  -2608.01431969  10831.06771944] 3.511013702057216e-12


3. Создайте функцию calc_pred_proba, возвращающую предсказанную вероятность класса 1 (на вход подаются W, который уже посчитан функцией eval_model и X, на выходе - массив y_pred_proba).

In [15]:
def calc_predict_proba(W, X):
    
    y_pred_proba = sigmoid(np.dot(W.T, X))
    
    return y_pred_proba

In [16]:
calc_predict_proba(W, X_st)

array([2.28965313e-49, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
       1.00000000e+00, 3.51101538e-11, 1.00000000e+00, 0.00000000e+00,
       1.00000000e+00, 1.00000000e+00])

4. Создайте функцию calc_pred, возвращающую предсказанный класс (на вход подаются W, который уже посчитан функцией eval_model и X, на выходе - массив y_pred).

In [17]:
def calc_pred(W, X):
    #     За порог отнесения к тому или иному классу примем вероятность 0.5
    y_pred = np.sign(sigmoid(np.dot(W.T, X))-0.5)
    y_pred = np.maximum(y_pred, np.zeros(len(y_pred)))
    
    return y_pred

In [18]:
y_pred = calc_pred(W, X_st)
y_pred

array([0., 0., 1., 0., 1., 0., 1., 0., 1., 1.])

5. Посчитайте Accuracy, матрицу ошибок, точность и полноту, а также F1 score.

In [19]:
Accuracy = np.mean([y_pred == y])*100
Accuracy

100.0

In [20]:
err_matrix = np.array([[np.sum((y_pred == 1) & (y==1)), np.sum((y_pred == 1) & (y==-1))],
        [np.sum((y_pred == -1) & (y==1)), np.sum((y_pred == -1) & (y==-1))]])
err_matrix

array([[5, 0],
       [0, 0]])

In [21]:
precision = err_matrix[0][0]/(err_matrix[0][0] + err_matrix[0][1])
precision

1.0

In [22]:
recall = err_matrix[0][0]/(err_matrix[0][0] + err_matrix[1][0])
recall

1.0

In [23]:
F = 2 * precision * recall / (precision + recall)
F

1.0

6. Могла ли модель переобучиться? Почему?

Да, как и любая линейная модель. В частности, это произошло во втором задании.

7 (опциональное): Создайте функции eval_model_l1 и eval_model_l2 с применением L1 и L2 регуляризаций соответственно.

In [33]:
def eval_model_l2(X, y, iterations, alpha=1e-4, lambda_=0.05):
    np.random.seed(42)
    W = np.random.randn(X.shape[0])
    n = X.shape[1]
    for i in range(1, iterations+1):
        z = np.dot(W, X)
        y_pred = sigmoid(z)
        err = calc_logloss(y, y_pred)
        W -= alpha * (1/n * np.dot((y_pred - y), X.T) + 2 * lambda_ * W)
        if i % (iterations / 10) == 0:
            print(i, W, err)
    return W

In [34]:
def eval_model_l1(X, y, iterations, alpha=1e-4, lambda_=0.05):
    np.random.seed(42)
    W = np.random.randn(X.shape[0])
    n = X.shape[1]
    for i in range(1, iterations+1):
        z = np.dot(W, X)
        y_pred = sigmoid(z)
        err = calc_logloss(y, y_pred)
        W -= alpha * (1/n * np.dot((y_pred - y), X.T) +  lambda_ * np.sign(W))
        if i % (iterations / 10) == 0:
            print(i, W, err)
    return W

In [35]:
W = eval_model_l2(X_st, y, iterations=5000, alpha=1e-4, lambda_=0.05)

500 [ 0.4758088  -0.20827928  0.64282618  1.48781335] 1.0521725791616885
1000 [ 0.45605974 -0.27423583  0.63750609  1.45414811] 0.9386960705987007
1500 [ 0.43754426 -0.33549517  0.63188457  1.42227544] 0.8396624884010067
2000 [ 0.42033223 -0.39124786  0.62622631  1.39250014] 0.7563621656738959
2500 [ 0.40448359 -0.44056525  0.62087056  1.36516127] 0.689759871073359
3000 [ 0.39002012 -0.48272237  0.616135    1.34051957] 0.6395633660685575
3500 [ 0.37689167 -0.51759465  0.61220687  1.31862851] 0.6036932982705596
4000 [ 0.3649759  -0.54573639  0.60910969  1.29931105] 0.5789297604645018
4500 [ 0.35411245 -0.56810646  0.60675498  1.28224985] 0.5620535576681437
5000 [ 0.34413955 -0.58574205  0.60501254  1.26709427] 0.5505146172012315


In [36]:
W = eval_model_l1(X_st, y, iterations=5000, alpha=1e-4, lambda_=0.05)

500 [ 0.47571771 -0.20671187  0.64356301  1.49281107] 1.057033487213347
1000 [ 0.45572828 -0.27159665  0.63896814  1.46390232] 0.9470862064651907
1500 [ 0.4368245  -0.33230814  0.6340402   1.43653205] 0.8502160823060304
2000 [ 0.41907775 -0.388082    0.62901599  1.41098725] 0.767694527034461
2500 [ 0.40255219 -0.43802054  0.62420973  1.38759564] 0.7005882536320452
3000 [ 0.38728241 -0.48134942  0.61993407  1.36663459] 0.6489679244603883
3500 [ 0.37324108 -0.51779186  0.61639769  1.34820863] 0.6112909291422625
4000 [ 0.36033104 -0.54771491  0.6136575   1.33220412] 0.584773694721169
4500 [ 0.34841134 -0.57193374  0.61165224  1.31835407] 0.5663974205569955
5000 [ 0.33733204 -0.59140605  0.61026694  1.30633811] 0.5536397499412529
